# Generated by Django 5.2.7 on 2025-11-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
